kind: PersistentVolume
apiVersion: v1
metadata:
  name: mongodb-volume
  labels:
    type: local
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/mongodb-volume"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongodb-volume-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: mongodb-volume
  resources:
    requests:
      storage: 500Mi