apiVersion: apps/v1
kind: Deployment
metadata:
  name: scores-microservice
spec:
  selector:
    matchLabels:
      app: scores-microservice
  replicas: 2
  template:
    metadata:
      labels:
        app: scores-microservice
    spec:
      containers:
      - name: scores-microservice
        image: gmicsa/scores-microservice:0.0.3
        imagePullPolicy: Never
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: dev
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: scores-microservice-service
spec:
  type: LoadBalancer
  ports:
  - port: 8080
  selector:
    app: scores-microservice
