version: '3'

services:
  scores-microservice:
    build: ..
    image: gmicsa/scores-microservice:0.0.3
    ports:
     - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
    links:
     - mongodb
    depends_on:
    - mongodb
    restart: always
  mongodb:
    image: mongo:5.0.3
    volumes:
     - /data/db:/data/db
    ports:
     - "27017:27017"
    restart: always
