spring:
  data:
    mongodb:
      database: scores
      host: localhost
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always