version: '3'

services:
  scores-microservice:
    build: ..
    image: gmicsa/scores-microservice:0.0.1
    container_name: scores-microservice1
    ports:
     - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
    links:
     - mongodb
    restart: always
  mongodb:
    image: mongo:3.0.2
    container_name: mongodb
    ports:
     - "27017:27017"
    restart: always
